stages:
  - test
test:
  stage: test
  image: kariae/symfony-php
  tags:
    - test
  services:
    - postgres
variables:
    POSTGRES_USER: lekode-test
    POSTGRES_PASSWORD: lekode-test-pass
    POSTGRES_DB: lekode-db
    DATABASE_HOST: postgres
    DATABASE_PORT: "5432"
artifacts:
    expire_in: 1 day
    paths:
      - vendor/
      - app/config/parameters.yml
      - var/bootstrap.php.cache
before_script:
    - composer config cache-files-dir /cache/composer
cache:
    paths:
      - /cache/composer
      - ./vendor
script:
    - composer install --optimize-autoloader
    - vendor/bin/simple-phpunit
