# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    app.form_login_authenticator:
        class: AppBundle\Security\FormLoginAuthenticator
        arguments: ["@router", "@security.password_encoder"]

    admin.recipe:
        class: AppBundle\Admin\RecipeAdmin
        arguments: [~, AppBundle\Entity\Recipe, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Recipe, label: Recipe }

    admin.ingredient:
        class: AppBundle\Admin\IngredientAdmin
        arguments: [~, AppBundle\Entity\Ingredient, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Recipe, label: Ingredient }

    admin.recipe_has_ingredient:
        class: AppBundle\Admin\RecipeHasIngredientAdmin
        arguments: [~, AppBundle\Entity\RecipeHasIngredient, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: RecipeHasIngredient }

    admin.ingredient_has_unit:
        class: AppBundle\Admin\IngredientHasUnitAdmin
        arguments: [~, AppBundle\Entity\IngredientHasUnit, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: IngredientHasUnit }

    admin.step:
        class: AppBundle\Admin\StepAdmin
        arguments: [~, AppBundle\Entity\Step, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Recipe, label: Step }

    admin.timer:
        class: AppBundle\Admin\TimerAdmin
        arguments: [~, AppBundle\Entity\Timer, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Recipe, label: Timer }

    admin.unit:
        class: AppBundle\Admin\UnitAdmin
        arguments: [~, AppBundle\Entity\Unit, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Recipe, label: Unit }

    admin.part:
        class: AppBundle\Admin\PartAdmin
        arguments: [~, AppBundle\Entity\Part, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Recipe, label: Part }

## Twig Extension
    app.twig_extension:
        class: AppBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }

parameters:
    sonata.media.admin.media.class: AppBundle\Admin\MediaAdmin
